// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBphgSMO2lJl_TJjV7N3Th97yzfOWXD1vw',
    appId: '1:807639676943:web:cea23c24575666f566cb7a',
    messagingSenderId: '807639676943',
    projectId: 'dowdow-dev',
    authDomain: 'dowdow-dev.firebaseapp.com',
    storageBucket: 'dowdow-dev.firebasestorage.app',
    measurementId: 'G-7XZ8KXCWNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Y6s2IhrwmAv9p6COqg_0ieWiHsuAAYM',
    appId: '1:807639676943:android:b7bf8f24c7fc78db66cb7a',
    messagingSenderId: '807639676943',
    projectId: 'dowdow-dev',
    storageBucket: 'dowdow-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgzsFnRB10zc4eXGahgoIDtSzYyzvoqtU',
    appId: '1:807639676943:ios:8db93d7cbf6e9aec66cb7a',
    messagingSenderId: '807639676943',
    projectId: 'dowdow-dev',
    storageBucket: 'dowdow-dev.firebasestorage.app',
    iosBundleId: 'com.jsengr.dawdaw',
  );

}